before:
  hooks:
  - go mod tidy
  - ./scripts/completions.sh
builds:
- binary: go-blueprint
  main: ./
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X cmd.GoBlueprintVersion={{.Version}}

release:
  prerelease: auto

universal_binaries:
- replace: true

brews:
- name: go-blueprint
  homepage: "https://github.com/Melkeydev/homebrew-melkey"
  taps:
    owner: Melkeydev
    name: homebrew-melkey

checksum:
  name_template: 'checksums.txt'
