FROM golang:1.23-alpine AS build

RUN apk add --no-cache make curl{{- if and (.AdvancedOptions.docker) (eq .DBDriver "sqlite") }} alpine-sdk{{ end }}

WORKDIR /app

COPY . .
RUN go mod download

{{- if or .AdvancedOptions.htmx .AdvancedOptions.tailwind }}
RUN go install github.com/a-h/templ/cmd/templ@latest
RUN templ generate
{{- end}}

{{- if .AdvancedOptions.tailwind}}
RUN curl -sL https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -o tailwindcss && chmod +x tailwindcss
RUN ./tailwindcss -i cmd/web/assets/css/input.css -o cmd/web/assets/css/output.css
{{- end }}

RUN {{ if (eq .DBDriver "sqlite") }}CGO_ENABLED=1 GOOS=linux {{ end }}go build -o main cmd/api/main.go

FROM alpine:3.20.1 AS prod
WORKDIR /app
COPY --from=build /app/main /app/main
EXPOSE ${PORT}
CMD ["./main"]
