FROM golang:1.23-alpine AS build
{{- if or (.AdvancedOptions.tailwind) (eq .DBDriver "sqlite") }}
RUN apk add --no-cache{{- if .AdvancedOptions.tailwind }} curl{{ end }}{{- if (eq .DBDriver "sqlite") }} alpine-sdk{{ end }}
{{- end }}

WORKDIR /app

COPY . .

RUN go mod download{{ if or .AdvancedOptions.htmx .AdvancedOptions.tailwind }} && \{{- end}}

{{- if or .AdvancedOptions.htmx .AdvancedOptions.tailwind }}
    go install github.com/a-h/templ/cmd/templ@latest && \
    templ generate{{- if .AdvancedOptions.tailwind}} && \{{- end}}
{{- end}}

{{- if .AdvancedOptions.tailwind}}
    curl -sL https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -o tailwindcss && \
    chmod +x tailwindcss && \
    ./tailwindcss -i cmd/web/assets/css/input.css -o cmd/web/assets/css/output.css
{{- end }}

RUN {{ if (eq .DBDriver "sqlite") }}CGO_ENABLED=1 GOOS=linux {{ end }}go build -o main cmd/api/main.go

FROM alpine:3.20.1 AS prod
WORKDIR /app
COPY --from=build /app/main /app/main
EXPOSE ${PORT}
CMD ["./main"]
