name: Check for new htmx release

on:
  schedule:
    - cron: '0 0 * * Sun'
  workflow_dispatch:

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get version from file
        id: get_version_file
        run: |
          VERSION_FILE=$(curl https://raw.githubusercontent.com/Melkeydev/go-blueprint/main/cmd/template/advanced/files/htmx/htmx.min.js.tmpl | grep version | awk -F'"' '{print "v" $2}')
          echo "version file: $VERSION_FILE"

      - name: Get version from GitHub API
        id: get_version_api
        run: |
          VERSION_API=$(curl -s https://api.github.com/repos/bigskysoftware/htmx/releases/latest | jq -r '.tag_name')
          echo "version api: $VERSION_API"

      - name: Compare versions
        id: compare_versions
        run: |
          if [ "$VERSION_API" != "$VERSION_FILE" ]; then
            echo "release_changed=true" >> $GITHUB_OUTPUT
            echo "Release changed: true"
          else
            echo "release_changed=false" >> $GITHUB_OUTPUT
            echo "Release changed: false"
          fi

      - name: Call workflow to build code
        if: steps.compare_versions.outputs.release_changed == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update-htmx-version.yml
