name: npm-publish

on:
  workflow_call:
    inputs:
      tag:
        description: 'Release tag to publish (e.g., v1.0.0)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to publish (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      
      - name: Download release assets
        run: |
          TAG="${{ inputs.tag }}"
          VERSION=${TAG#v}
          mkdir -p dist
          gh release download "$TAG" --dir dist
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create npm packages
        run: |
          chmod +x ./scripts/create-npm-packages.sh
          ./scripts/create-npm-packages.sh "$VERSION"

      - name: Publish platform-specific packages to npm
        run: |
          for platform_dir in platform-packages/go-blueprint-*; do
            if [ -d "$platform_dir" ]; then
              cd "$platform_dir"
              npm publish --access public
              cd - > /dev/null
            fi
          done

      - name: Publish main package to npm
        run: |
          cd npm-package
          npm publish --access public