name: NPM Publisher

on:
  workflow_call:
    inputs:
      tag:
        description: 'Release tag to publish (e.g., v1.0.0)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to publish (e.g., v1.0.0)'
        required: true
        type: string

env:
  NODE_VERSION: '22'
  REGISTRY_URL: 'https://registry.npmjs.org'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.REGISTRY_URL }}
      
      - name: Extract version and download release assets
        run: |
          TAG="${{ inputs.tag }}"
          VERSION=${TAG#v}
          
          mkdir -p dist
          gh release download "$TAG" --dir dist
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate NPM package structure
        run: |
          chmod +x ./scripts/create-npm-packages.sh
          ./scripts/create-npm-packages.sh "$VERSION"
          
      - name: Configure NPM authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish platform-specific packages
        run: |
          for platform_dir in platform-packages/go-blueprint-*; do
            if [ -d "$platform_dir" ]; then
              cd "$platform_dir"
              npm publish --access public
              cd - > /dev/null
            fi
          done
          
      - name: Publish main package
        run: |
          cd npm-package
          npm publish --access public